<?php
    session_start();
    session_destroy();
    unset($_SESSION['login_name']);
    unset($_SESSION['login_picture']);
    unset($_SESSION['login_id']);
    unset($_SESSION['login_pass']);
    header('Location:login.php');
?>